 - name: Install apache on devservers
   when: ansible_hostname == "app"
   yum:
     name: httpd
     state: latest
          
 - name: ensure httpd is running
   when: ansible_hostname == "app"
   systemd:
     name: httpd 
     state: started
     enabled: yes

 - name: Check status of httpd service
   when: ansible_hostname == "app"
   service_facts:
   register: service_state
 - debug:
     var: service_state.ansible_facts.services["httpd.service"].state