---
  - name: Users Management
    hosts: "{{ group }}"
    gather_facts: "{{ gather_facts }}"
    vars_files:
      - "../variables/addusers-values.yaml"
    tasks:

    # Task for user1 - values defined in ../variables/addusers-values.yaml

      - name: user 1
        user:
          name: "{{ user_name1}}"
          uid: "{{ user1_uid }}"
    # Task for user2 - values defined in ../variables/addusers-values.yaml

      - name: user 2
        user:
          name: "{{ user_name2 }}"
          uid: "{{ user2_uid }}"
    