---
  - name: create empty file
    hosts: "{{ group }}"
    gather_facts: "{{ gather_facts }}"
    vars_files:
      - "../variables/file-values.yaml"
    tasks:
      - name: Change file ownership, group and permissions
        file:
          path: /tmp/{{ file_name}}
          content: 
          state: "{{ file_state }}"
          mode: "{{ file_mode }}"

      - name: add a line to the file
        lineinfile:
          path: /tmp/{{file_name}}
          line: "{{ add_a_line }}"
          create: yes 
      
      - name: add a line to the file
        blockinfile:
          path: /tmp/{{ file_name }}
          block: |
            {{ block }}
          
        