# List of Fruits
fruits: 
  - apple
  - banana
  - orange

# List of Vegetables

vegetables:
  - watemelon
  - potato
  - onion

# Grocery list
items:      #This is the main ist
  fruits:      #This is the fruits list in the main list
    - apple
    - banana
    - orange
  vegetables:   # this is vegetables list in the main list
    - watermelon
    - potato
    - onion 
