---
  - name:  run command and get the output
    hosts: development
    gather_facts: no
    tasks:
      - name: ping the servers
        ping:

      - name: run command "ls"
        command: "{{item}}"
        with_items:
          - ls
          - pwd   
        register: command_output

      - name: Run debug to read command_output
        debug: 
          var: command_output