---
  - hosts: development
    tasks:
      - name: Ansible create file if it doesn't exist example
        file:
          path: /tmp/testfile2
          state: absent
          #mode: u+rwx,g+rw,o+r