---
  - name: Update all Packages
    hosts: dev-servers
    tasks:
      - name: Ping hosts
        ping:

      - name: Update packages
        yum: 
          name: '*'
          state: latest
          update_cache: yes