---
  - name: Host Variable
    hosts: "{{ group }}"
    vars_files:
      - "../variables/values-variables.yaml"
    tasks:

      - name: Install yum packages
        yum: 
          name: "{{ package }}"